# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 02:32
from __future__ import unicode_literals

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_apoio', enumfields.fields.EnumField(default=0, enum=apps.core.models.TipoApoio, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ApoioEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apoio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apoio')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('tipo_atividade', enumfields.fields.EnumField(default=0, enum=apps.core.models.TipoAtividade, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('cod_cupom', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='desconto')),
                ('validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('cod_evento', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo_evento', enumfields.fields.EnumField(default=0, enum=apps.core.models.TipoEvento, max_length=10)),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('estado_evento', enumfields.fields.EnumField(default=0, enum=apps.core.models.EstadoEvento, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapagamento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TagEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Evento')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='cupom',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Evento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='apoioevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Evento'),
        ),
        migrations.AddField(
            model_name='apoio',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Instituicao'),
        ),
    ]
