# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 21:22
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoio',
            fields=[
                ('cod_apoio', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_de_apoio', enumfields.fields.EnumField(default=0, enum=core.models.TipoApoio, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('cod_atividade', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('tipo_atividade', enumfields.fields.EnumField(default=0, enum=core.models.TipoAtividade, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('cod_cupom', models.IntegerField(primary_key=True, serialize=False)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='desconto')),
                ('validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('cod_evento', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo_evento', enumfields.fields.EnumField(default=0, enum=core.models.TipoEvento, max_length=10)),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('estado_evento', enumfields.fields.EnumField(default=0, enum=core.models.EstadoEvento, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('cod_inscricao', models.IntegerField(primary_key=True, serialize=False)),
                ('data_inscricao', models.DateTimeField()),
                ('valor', models.FloatField()),
                ('estado_inscricao', enumfields.fields.EnumField(default=0, enum=core.models.EstadoInscricao, max_length=10)),
                ('dia_pagamento', models.DateField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('cod_instituicao', models.IntegerField(primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cod_user', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=45)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='inscricao',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='evento',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='evento',
            name='atividades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Atividade'),
        ),
        migrations.AddField(
            model_name='cupom',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Evento'),
        ),
        migrations.AddField(
            model_name='apoio',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apoios', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='apoio',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Instituicao'),
        ),
    ]
