# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170810_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cod_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
