# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170810_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='login',
            new_name='username',
        ),
    ]
