# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 12:57
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170811_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapagamento', models.DateField()),
                ('status', enumfields.fields.EnumField(default=0, enum=core.models.EstadoInscricao, max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='solicitante',
        ),
        migrations.DeleteModel(
            name='Inscricao',
        ),
    ]
