# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 17:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nomedeusuario', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('cod_inscricao', models.IntegerField(primary_key=True, serialize=False)),
                ('data_inscricao', models.DateTimeField()),
                ('valor', models.FloatField()),
                ('dia_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pagamento')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Evento')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Atividade')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Inscricao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
